export const DEFAULT_KNOWLEDGE_ENTRIES_PAGE_SIZE = 50
export const DEFAULT_SIDEBAR_FILES_PAGE_SIZE = 25
export const MAX_KNOWLEDGE_ENTRIES_PAGE_SIZE = 100
export const MAX_SIDEBAR_FILES_PAGE_SIZE = 50
