import type { Message } from '@/types/database'

const LEGACY_AI_ECHO_MAX_DELTA_MS = 60_000
const LEGACY_IMAGE_ECHO_MAX_DELTA_MS = 90_000

function parseMetadataRecord(metadata: unknown) {
  if (typeof metadata === 'object' && metadata !== null && !Array.isArray(metadata)) {
    return metadata as Record<string, unknown>
  }

  if (typeof metadata !== 'string') return null
  const trimmed = metadata.trim()
  if (!trimmed) return null

  try {
    const parsed = JSON.parse(trimmed)
    if (typeof parsed === 'object' && parsed !== null && !Array.isArray(parsed)) {
      return parsed as Record<string, unknown>
    }
  } catch {
    return null
  }

  return null
}

function readTrimmedString(value: unknown) {
  if (typeof value !== 'string') return null
  const trimmed = value.trim()
  return trimmed.length > 0 ? trimmed : null
}

function parseTimestamp(value: unknown) {
  if (typeof value !== 'string') return null
  const time = Date.parse(value)
  return Number.isFinite(time) ? time : null
}

function hasAiDisclaimer(content: string) {
  return (
    content.includes('Bu mesaj AI bot tarafından oluşturuldu')
    || content.includes('This message was generated by an AI bot')
  )
}

function isInstagramImageMedia(metadata: Record<string, unknown> | null) {
  if (!metadata) return false

  if (readTrimmedString(metadata.instagram_media_type)?.toLowerCase() === 'image') {
    return true
  }

  const media = metadata.instagram_media
  if (typeof media !== 'object' || media === null || Array.isArray(media)) return false
  return readTrimmedString((media as Record<string, unknown>).type)?.toLowerCase() === 'image'
}

function isInstagramImageEcho(metadata: Record<string, unknown> | null) {
  if (metadata?.instagram_is_echo !== true) return false
  return isInstagramImageMedia(metadata)
}

export function filterInstagramEchoDuplicates(messages: Message[]) {
  const botProviderMessageIds = new Set<string>()
  const botAiMessages = new Map<string, number[]>()
  const botImageTimestamps: number[] = []

  for (const message of messages) {
    if (message.sender_type !== 'bot') continue

    const metadata = parseMetadataRecord(message.metadata)
    const instagramMessageId = readTrimmedString(metadata?.instagram_message_id)
    if (instagramMessageId) {
      botProviderMessageIds.add(instagramMessageId)
    }

    if (metadata?.skill_has_image === true && isInstagramImageMedia(metadata)) {
      const createdAt = parseTimestamp(message.created_at)
      if (createdAt !== null) {
        botImageTimestamps.push(createdAt)
      }
    }

    const content = readTrimmedString(message.content)
    if (!content || !hasAiDisclaimer(content)) continue

    const createdAt = parseTimestamp(message.created_at)
    if (createdAt === null) continue

    const timestamps = botAiMessages.get(content) ?? []
    timestamps.push(createdAt)
    botAiMessages.set(content, timestamps)
  }

  if (botProviderMessageIds.size === 0 && botAiMessages.size === 0 && botImageTimestamps.length === 0) {
    return messages
  }

  return messages.filter((message) => {
    if (message.sender_type !== 'user') return true

    const metadata = parseMetadataRecord(message.metadata)
    if (metadata?.instagram_is_echo !== true) return true

    const instagramMessageId = readTrimmedString(metadata.instagram_message_id)
    if (instagramMessageId && botProviderMessageIds.has(instagramMessageId)) {
      return false
    }

    const createdAt = parseTimestamp(message.created_at)
    if (isInstagramImageEcho(metadata) && createdAt !== null) {
      const isNearBotImage = botImageTimestamps.some((botTimestamp) => {
        return Math.abs(botTimestamp - createdAt) <= LEGACY_IMAGE_ECHO_MAX_DELTA_MS
      })
      if (isNearBotImage) return false
    }

    const content = readTrimmedString(message.content)
    if (!content || !hasAiDisclaimer(content) || createdAt === null) return true

    const matchingBotTimestamps = botAiMessages.get(content)
    if (!matchingBotTimestamps || matchingBotTimestamps.length === 0) return true

    return !matchingBotTimestamps.some((botTimestamp) => {
      return Math.abs(botTimestamp - createdAt) <= LEGACY_AI_ECHO_MAX_DELTA_MS
    })
  })
}
