export type OutboundTextPlatform = 'whatsapp' | 'telegram' | 'instagram'

export interface OutboundTextFormatOptions {
    platform: OutboundTextPlatform
    telegramParseMode?: string | null
}

const BOT_DISCLAIMER_FOOTERS = [
    'Bu mesaj AI bot tarafından oluşturuldu, hata içerebilir.',
    'This message was generated by an AI bot and may contain mistakes.'
]

function normalizeUrlWhitespace(rawUrl: string) {
    return rawUrl.replace(/\s+/g, '').trim()
}

function splitTrailingUrlPunctuation(url: string) {
    const trailingPunctuation = url.match(/[.,;:!?]+$/)?.[0] ?? ''
    if (!trailingPunctuation) {
        return { url, trailingPunctuation: '' }
    }

    return {
        url: url.slice(0, -trailingPunctuation.length),
        trailingPunctuation
    }
}

function formatRawUrlForPlainChat(rawUrl: string) {
    const compacted = normalizeUrlWhitespace(rawUrl)
    const { url, trailingPunctuation } = splitTrailingUrlPunctuation(compacted)
    const repairedUrl = url || compacted
    const hadWhitespace = /\s/.test(rawUrl)

    if (!hadWhitespace && !trailingPunctuation) {
        return repairedUrl
    }

    return `\n${repairedUrl}\n`
}

export function normalizeMarkdownLinksForPlainChat(content: string) {
    return content.replace(/\[([^\]\n]+)]\(\s*(https?:\/\/[\s\S]*?)\s*\)/gi, (_match, rawLabel: string, rawUrl: string) => {
        const label = rawLabel.trim()
        const url = normalizeUrlWhitespace(rawUrl)
        if (!label || label === url) return url
        if (/\s/.test(rawUrl)) return `${label}:\n${url}\n`
        return `${label}: ${url}`
    })
}

function normalizeRawUrlsForPlainChat(content: string) {
    return content.replace(
        /https?:\/\/[A-Za-z0-9._~:/?#[\]@!$&'()*+,;=%-]+(?:(?:\s+(?=[/?#])|(?<=[-_/=&#?%.])\s+)[A-Za-z0-9._~:/?#[\]@!$&'()*+,;=%-]+)*/gi,
        (rawUrl: string) => formatRawUrlForPlainChat(rawUrl)
    )
}

function normalizeUrlLineBreaks(content: string) {
    return content
        .replace(/[ \t]*\n[ \t]*/g, '\n')
        .replace(/\n[.,;:!?]+(?=\n|$)/g, '')
        .replace(/\n{3,}/g, '\n\n')
        .trim()
}

function convertDoubleStarToSingleStar(content: string) {
    return content.replace(/\*\*([^*\n][^*\n]*?)\*\*/g, (_match, value: string) => `*${value.trim()}*`)
}

function normalizeInlineBullets(content: string) {
    const bulletStartPattern = /\s+-\s+(?=(?:\*\*)?[A-Za-zÇĞİÖŞÜçğıöşü0-9])/g
    const matches = content.match(bulletStartPattern) ?? []
    const hasListIntro = /[:：]\s+-\s+(?=(?:\*\*)?[A-Za-zÇĞİÖŞÜçğıöşü0-9])/.test(content)
    if (!hasListIntro && matches.length < 2) return content

    return content
        .replace(/([:：])\s+-\s+(?=(?:\*\*)?[A-Za-zÇĞİÖŞÜçğıöşü0-9])/g, '$1\n- ')
        .replace(bulletStartPattern, '\n- ')
}

function stripPlainTextMarkdown(content: string) {
    return content
        .replace(/```[a-z0-9_-]*\n?/gi, '')
        .replace(/```/g, '')
        .replace(/`([^`\n]+)`/g, '$1')
        .replace(/^\s{0,3}#{1,6}\s+/gm, '')
        .replace(/^\s{0,3}>\s?/gm, '')
        .replace(/^\s*[-*_]{3,}\s*$/gm, '')
        .replace(/\*\*([^*\n]+)\*\*/g, '$1')
        .replace(/__([^_\n]+)__/g, '$1')
        .replace(/\*([^*\n]+)\*/g, '$1')
        .replace(/[ \t]+\n/g, '\n')
        .replace(/\n{3,}/g, '\n\n')
        .trim()
}

function escapeRegExp(value: string) {
    return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function normalizeBotDisclaimerFooter(content: string, options: { quoteFooter: boolean }) {
    let normalized = content.replace(/[ \t]+\n/g, '\n').trim()

    for (const footer of BOT_DISCLAIMER_FOOTERS) {
        const escapedFooter = escapeRegExp(footer)
        const footerPattern = new RegExp(`\\s*(?:\\n\\s*)?>?\\s*${escapedFooter}\\s*$`, 'i')
        if (!footerPattern.test(normalized)) continue

        normalized = normalized.replace(footerPattern, '').trim()
        const formattedFooter = options.quoteFooter ? `> ${footer}` : footer
        return `${normalized}\n\n${formattedFooter}`.trim()
    }

    return normalized
}

export function formatOutboundTextForChannel(content: string, options: OutboundTextFormatOptions) {
    if (options.platform === 'telegram' && options.telegramParseMode) {
        return content
    }

    const withPlainLinks = normalizeUrlLineBreaks(
        normalizeInlineBullets(normalizeRawUrlsForPlainChat(normalizeMarkdownLinksForPlainChat(content)))
    )

    if (options.platform === 'whatsapp') {
        return normalizeBotDisclaimerFooter(convertDoubleStarToSingleStar(withPlainLinks), {
            quoteFooter: true
        })
    }

    const plainText = stripPlainTextMarkdown(withPlainLinks)
    if (options.platform === 'telegram') {
        return normalizeBotDisclaimerFooter(plainText, {
            quoteFooter: true
        })
    }

    return normalizeBotDisclaimerFooter(plainText, {
        quoteFooter: true
    })
}
