import { describe, expect, it } from 'vitest'
import { formatOutboundTextForChannel } from './outbound-text-format'

describe('formatOutboundTextForChannel', () => {
    it('converts double-star emphasis to WhatsApp single-star emphasis and keeps full URLs', () => {
        const formatted = formatOutboundTextForChannel(
            '**Tıp Fakültesi:** Detaylar için [sayfayı aç](https://example.com/tip).',
            { platform: 'whatsapp' }
        )

        expect(formatted).toBe('*Tıp Fakültesi:* Detaylar için sayfayı aç:\nhttps://example.com/tip')
    })

    it('converts spaced Markdown URLs into raw clickable WhatsApp links', () => {
        const formatted = formatOutboundTextForChannel(
            '2025-2026 Eğitim Öğretim Yılı Akademik Takvimine şu linkten ulaşabilirsiniz: [2025-2026 Eğitim Öğretim Yılı Akademik Takvimi](https://yuksekihtisasuniversitesi. edu. tr/sayfa/ogrenci/akademik-takvim/2025-2026-egitim-ogretim-yili-akademik-takvimi).',
            { platform: 'whatsapp' }
        )

        expect(formatted).toBe(
            '2025-2026 Eğitim Öğretim Yılı Akademik Takvimine şu linkten ulaşabilirsiniz: 2025-2026 Eğitim Öğretim Yılı Akademik Takvimi:\nhttps://yuksekihtisasuniversitesi.edu.tr/sayfa/ogrenci/akademik-takvim/2025-2026-egitim-ogretim-yili-akademik-takvimi'
        )
    })

    it('converts newline-wrapped Markdown URLs into isolated raw WhatsApp links', () => {
        const formatted = formatOutboundTextForChannel(
            'Güncel akademik takvim için [akademik takvim](https://yuksekihtisasuniversitesi.edu.tr/tr/akademik/\nakademik-takvim) bağlantısını inceleyebilirsiniz.',
            { platform: 'whatsapp' }
        )

        expect(formatted).toBe(
            'Güncel akademik takvim için akademik takvim:\nhttps://yuksekihtisasuniversitesi.edu.tr/tr/akademik/akademik-takvim\nbağlantısını inceleyebilirsiniz.'
        )
    })

    it('repairs spaces inside raw URLs without swallowing following text', () => {
        const formatted = formatOutboundTextForChannel(
            'Akademik takvim: https://yuksekihtisasuniversitesi. edu. tr/sayfa/ogrenci/akademik-takvim üzerinden açabilirsiniz.',
            { platform: 'whatsapp' }
        )

        expect(formatted).toBe(
            'Akademik takvim:\nhttps://yuksekihtisasuniversitesi.edu.tr/sayfa/ogrenci/akademik-takvim\nüzerinden açabilirsiniz.'
        )
    })

    it('repairs whitespace inside raw URL paths without swallowing Turkish prose', () => {
        const formatted = formatOutboundTextForChannel(
            'Final tarihleri için https://yuksekihtisasuniversitesi.edu.tr/tr/akademik/\nakademik-takvim üzerinden bilgi alabilirsiniz.',
            { platform: 'whatsapp' }
        )

        expect(formatted).toBe(
            'Final tarihleri için\nhttps://yuksekihtisasuniversitesi.edu.tr/tr/akademik/akademik-takvim\nüzerinden bilgi alabilirsiniz.'
        )
    })

    it('repairs whitespace before a raw URL path slash', () => {
        const formatted = formatOutboundTextForChannel(
            'Takvim: https://example.edu.tr /akademik-takvim üzerinden açılır.',
            { platform: 'whatsapp' }
        )

        expect(formatted).toBe(
            'Takvim:\nhttps://example.edu.tr/akademik-takvim\nüzerinden açılır.'
        )
    })

    it('keeps trailing punctuation outside raw WhatsApp URL tokens', () => {
        const formatted = formatOutboundTextForChannel(
            'Akademik takvim: https://example.edu.tr/akademik-takvim.',
            { platform: 'whatsapp' }
        )

        expect(formatted).toBe('Akademik takvim:\nhttps://example.edu.tr/akademik-takvim')
    })

    it('keeps WhatsApp bot disclaimers on a separate quoted footer line', () => {
        const formatted = formatOutboundTextForChannel(
            "Evet, Tıp Fakültesi'nde İngilizce eğitim verilmektedir.\nBu mesaj AI bot tarafından oluşturuldu, hata içerebilir.",
            { platform: 'whatsapp' }
        )

        expect(formatted).toBe(
            "Evet, Tıp Fakültesi'nde İngilizce eğitim verilmektedir.\n\n> Bu mesaj AI bot tarafından oluşturuldu, hata içerebilir."
        )
    })

    it('keeps Telegram bot disclaimers on a separate quoted footer line when plain text is used', () => {
        const formatted = formatOutboundTextForChannel(
            "Yes, English education is available.\nThis message was generated by an AI bot and may contain mistakes.",
            { platform: 'telegram' }
        )

        expect(formatted).toBe(
            "Yes, English education is available.\n\n> This message was generated by an AI bot and may contain mistakes."
        )
    })

    it('removes markdown markers for Instagram while keeping full URLs', () => {
        const formatted = formatOutboundTextForChannel(
            '**Tıp Fakültesi:**\n> Detaylar için [sayfayı aç](https://example.com/tip).',
            { platform: 'instagram' }
        )

        expect(formatted).toBe('Tıp Fakültesi:\nDetaylar için sayfayı aç:\nhttps://example.com/tip')
    })

    it('keeps Instagram bot disclaimers on a separate quoted footer line', () => {
        const formatted = formatOutboundTextForChannel(
            "Evet, Tıp Fakültesi'nde İngilizce eğitim verilmektedir.\nBu mesaj AI bot tarafından oluşturuldu, hata içerebilir.",
            { platform: 'instagram' }
        )

        expect(formatted).toBe(
            "Evet, Tıp Fakültesi'nde İngilizce eğitim verilmektedir.\n\n> Bu mesaj AI bot tarafından oluşturuldu, hata içerebilir."
        )
    })

    it('turns inline dash-separated list items into readable message bullets', () => {
        const formatted = formatOutboundTextForChannel(
            'Eğitim süreci şu şekildedir: - **Dersler:** Temel tıp bilimleri verilir. - **Klinik Beceri Eğitimi:** Birinci sınıftan itibaren başlar.',
            { platform: 'instagram' }
        )

        expect(formatted).toBe(
            'Eğitim süreci şu şekildedir:\n- Dersler: Temel tıp bilimleri verilir.\n- Klinik Beceri Eğitimi: Birinci sınıftan itibaren başlar.'
        )
    })

    it('sends Telegram as plain text when parse mode is not configured', () => {
        const formatted = formatOutboundTextForChannel(
            '**Tıp Fakültesi:**\n- [Detay](https://example.com/tip)',
            { platform: 'telegram' }
        )

        expect(formatted).toBe('Tıp Fakültesi:\n- Detay: https://example.com/tip')
    })

    it('keeps Telegram markdown when a parse mode is configured', () => {
        const formatted = formatOutboundTextForChannel(
            '**Tıp Fakültesi:**\n- [Detay](https://example.com/tip)',
            { platform: 'telegram', telegramParseMode: 'Markdown' }
        )

        expect(formatted).toBe('**Tıp Fakültesi:**\n- [Detay](https://example.com/tip)')
    })

    it.each([
        {
            name: 'program list',
            platform: 'whatsapp' as const,
            raw: '**Akademik Birimler:** - **Tıp Fakültesi** - **Sağlık Bilimleri Fakültesi** - **Sağlık Hizmetleri MYO**',
            expected: '*Akademik Birimler:*\n- *Tıp Fakültesi*\n- *Sağlık Bilimleri Fakültesi*\n- *Sağlık Hizmetleri MYO*'
        },
        {
            name: 'medicine education summary',
            platform: 'whatsapp' as const,
            raw: 'Eğitim süreci şu şekildedir: - **Dersler:** Temel tıp bilimleri verilir. - **Klinik Beceri Eğitimi:** Birinci sınıftan itibaren başlar. - **Staj ve Klinik Uygulamalar:** Sağlık kuruluşlarında yapılır.',
            expected: 'Eğitim süreci şu şekildedir:\n- *Dersler:* Temel tıp bilimleri verilir.\n- *Klinik Beceri Eğitimi:* Birinci sınıftan itibaren başlar.\n- *Staj ve Klinik Uygulamalar:* Sağlık kuruluşlarında yapılır.'
        },
        {
            name: 'horizontal transfer link',
            platform: 'instagram' as const,
            raw: '**Yatay geçiş** başvuruları için [resmi sayfayı](https://example.edu.tr/yatay-gecis) inceleyebilirsiniz.',
            expected: 'Yatay geçiş başvuruları için resmi sayfayı: https://example.edu.tr/yatay-gecis inceleyebilirsiniz.'
        },
        {
            name: 'erasmus requirements',
            platform: 'telegram' as const,
            raw: '**Erasmus şartları:** - **Lisans:** En az 2.20/4.00 GANO. - **Yüksek lisans/doktora:** En az 2.50/4.00 GANO.',
            expected: 'Erasmus şartları:\n- Lisans: En az 2.20/4.00 GANO.\n- Yüksek lisans/doktora: En az 2.50/4.00 GANO.'
        },
        {
            name: 'fees link',
            platform: 'instagram' as const,
            raw: '> Güncel ücretler için [ücretler sayfasına](https://example.edu.tr/ucretler) bakabilirsiniz.',
            expected: 'Güncel ücretler için ücretler sayfasına: https://example.edu.tr/ucretler bakabilirsiniz.'
        }
    ])('formats RAG-like outgoing answer: $name', ({ platform, raw, expected }) => {
        expect(formatOutboundTextForChannel(raw, { platform })).toBe(expected)
    })
})
