import type { OrganizationAiSettings } from '@/types/database'

export const DEFAULT_BOT_DISCLAIMER_MESSAGE_TR = 'Bu mesaj AI bot tarafından oluşturuldu, hata içerebilir.'
export const DEFAULT_BOT_DISCLAIMER_MESSAGE_EN = 'This message was generated by an AI bot and may contain mistakes.'

type BotDisclaimerSettings = Pick<
    Partial<OrganizationAiSettings>,
    'bot_disclaimer_enabled' | 'bot_disclaimer_message_tr' | 'bot_disclaimer_message_en'
>

function resolveDisclaimerMessage(
    responseLanguage: 'tr' | 'en',
    settings: BotDisclaimerSettings
) {
    const localizedMessage = responseLanguage === 'tr'
        ? settings.bot_disclaimer_message_tr
        : settings.bot_disclaimer_message_en

    const trimmed = (localizedMessage ?? '').toString().trim()
    if (trimmed) return trimmed

    return responseLanguage === 'tr'
        ? DEFAULT_BOT_DISCLAIMER_MESSAGE_TR
        : DEFAULT_BOT_DISCLAIMER_MESSAGE_EN
}

export function applyBotMessageDisclaimer(options: {
    message: string
    responseLanguage: 'tr' | 'en'
    settings: BotDisclaimerSettings
}) {
    const baseMessage = options.message.trim()
    if (!baseMessage) return ''

    if (options.settings.bot_disclaimer_enabled === false) {
        return baseMessage
    }

    const disclaimerMessage = resolveDisclaimerMessage(options.responseLanguage, options.settings)
    return `${baseMessage}\n\n> ${disclaimerMessage}`
}
