import type { OrganizationAiSettings } from '@/types/database'
import {
    isMvpResponseLanguageAmbiguous,
    resolveMvpResponseLanguage,
    type MvpResponseLanguage
} from '@/lib/ai/language'

export const DEFAULT_BOT_DISCLAIMER_MESSAGE_TR = 'Bu mesaj AI bot tarafından oluşturuldu, hata içerebilir.'
export const DEFAULT_BOT_DISCLAIMER_MESSAGE_EN = 'This message was generated by an AI bot and may contain mistakes.'

type BotDisclaimerSettings = Pick<
    Partial<OrganizationAiSettings>,
    'bot_disclaimer_enabled' | 'bot_disclaimer_message_tr' | 'bot_disclaimer_message_en'
>

type BotDisclaimerPlatform = 'whatsapp' | 'telegram' | 'instagram'

function resolveDisclaimerMessage(
    responseLanguage: 'tr' | 'en',
    settings: BotDisclaimerSettings
) {
    const localizedMessage = responseLanguage === 'tr'
        ? settings.bot_disclaimer_message_tr
        : settings.bot_disclaimer_message_en

    const trimmed = (localizedMessage ?? '').toString().trim()
    if (trimmed) return trimmed

    return responseLanguage === 'tr'
        ? DEFAULT_BOT_DISCLAIMER_MESSAGE_TR
        : DEFAULT_BOT_DISCLAIMER_MESSAGE_EN
}

function formatDisclaimerBlock(platform: BotDisclaimerPlatform | undefined, disclaimerMessage: string) {
    if (platform === 'instagram') {
        return `------\n> ${disclaimerMessage}`
    }

    return `> ${disclaimerMessage}`
}

function escapeRegExp(value: string) {
    return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function resolveKnownDisclaimerMessages(settings: BotDisclaimerSettings) {
    return Array.from(new Set([
        DEFAULT_BOT_DISCLAIMER_MESSAGE_TR,
        DEFAULT_BOT_DISCLAIMER_MESSAGE_EN,
        (settings.bot_disclaimer_message_tr ?? '').toString().trim(),
        (settings.bot_disclaimer_message_en ?? '').toString().trim()
    ].filter(Boolean)))
}

function stripModelSuppliedDisclaimerArtifacts(
    message: string,
    settings: BotDisclaimerSettings
) {
    let stripped = message.replace(/\r\n/g, '\n').trim()
    if (!stripped) return stripped

    const disclaimerMessages = resolveKnownDisclaimerMessages(settings)
    let previous = ''

    while (stripped && stripped !== previous) {
        previous = stripped

        for (const disclaimerMessage of disclaimerMessages) {
            const escapedMessage = escapeRegExp(disclaimerMessage)
            const trailingDisclaimerPattern = new RegExp(
                `(?:\\s*(?:-{4,}\\s*)?\\n?\\s*>?\\s*${escapedMessage}\\s*[.!?]*)+$`,
                'i'
            )

            stripped = stripped.replace(trailingDisclaimerPattern, '').trim()
        }
    }

    return stripped
}

function resolveDisclaimerLanguage(message: string, responseLanguage: MvpResponseLanguage): MvpResponseLanguage {
    if (isMvpResponseLanguageAmbiguous(message)) return responseLanguage
    return resolveMvpResponseLanguage(message)
}

export function applyBotMessageDisclaimer(options: {
    message: string
    responseLanguage: MvpResponseLanguage
    platform?: BotDisclaimerPlatform
    settings: BotDisclaimerSettings
}) {
    const baseMessage = stripModelSuppliedDisclaimerArtifacts(options.message, options.settings)
    if (!baseMessage) return ''

    if (options.settings.bot_disclaimer_enabled === false) {
        return baseMessage
    }

    const disclaimerLanguage = resolveDisclaimerLanguage(baseMessage, options.responseLanguage)
    const disclaimerMessage = resolveDisclaimerMessage(disclaimerLanguage, options.settings)
    return `${baseMessage}\n\n${formatDisclaimerBlock(options.platform, disclaimerMessage)}`
}
