-- Bot disclaimer settings (org-level)

ALTER TABLE public.organization_ai_settings
ADD COLUMN IF NOT EXISTS bot_disclaimer_enabled BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS bot_disclaimer_message_tr TEXT NOT NULL DEFAULT 'Bu mesaj AI bot tarafından oluşturuldu, hata içerebilir.',
ADD COLUMN IF NOT EXISTS bot_disclaimer_message_en TEXT NOT NULL DEFAULT 'This message was generated by an AI bot and may contain mistakes.';
